export type Cell = number;

export const SNAKES: Record<Cell, Cell> = {
  17: 4,
  34: 12,
  62: 41,
  87: 68,
  95: 76,
};

export const LADDERS: Record<Cell, Cell> = {
  3: 22,
  8: 26,
  28: 47,
  50: 71,
  66: 85,
  80: 99,
};

// Colors for snakes to give distinct physical appearance
export const SNAKE_COLORS = [
  { main: "#059669", accent: "#34d399", pattern: "#064e3b" }, // Emerald Green
  { main: "#dc2626", accent: "#f87171", pattern: "#7f1d1d" }, // Coral/Ruby Red
  { main: "#7c3aed", accent: "#a78bfa", pattern: "#4c1d95" }, // Royal Indigo
  { main: "#d97706", accent: "#fbbf24", pattern: "#78350f" }, // Amber/Copper
  { main: "#be185d", accent: "#f472b6", pattern: "#831843" }, // Crimson Maroon
];

export type StoryScene = {
  svgType:
    | "hanuman"
    | "sugriva"
    | "deer"
    | "jatayu"
    | "kaikeyi"
    | "bridge"
    | "rekha"
    | "shabari"
    | "lakshmana"
    | "ravana"
    | "sleep"
    | "victory"
    | "ayodhya"
    | "ocean"
    | "sanjeevani"
    | "default";
  primaryColor: string;
};

export type Moment = {
  square: Cell;
  kind: "snake" | "ladder" | "start" | "victory" | "story";
  chapter: string;
  title: string;
  text: string;
  valueOrLesson: string;
  scene: StoryScene;
};

// Comprehensive Ramayana Storyline mapping across all 100 squares
export const RAMAYANA_STORYLINE: Record<number, Moment> = {
  1: {
    square: 1,
    kind: "start",
    chapter: "BALA KANDA",
    title: "Birth in Ayodhya",
    text: "In golden Ayodhya on the Sarayu river, four noble princes are born to King Dasharatha: Rama, Lakshmana, Bharata, and Shatrughna.",
    valueOrLesson: "Virtue: Noble Beginnings & Harmony",
    scene: { svgType: "ayodhya", primaryColor: "#f59e0b" },
  },
  2: {
    square: 2,
    kind: "story",
    chapter: "BALA KANDA",
    title: "Vashistha's Ashram",
    text: "Under Sage Vashistha's gentle guidance, the young princes master the Vedas, ancient astronomy, archery, and the practice of dharma.",
    valueOrLesson: "Virtue: Thirst for Knowledge & Humility",
    scene: { svgType: "default", primaryColor: "#d97706" },
  },
  3: {
    square: 3,
    kind: "ladder",
    chapter: "BALA KANDA",
    title: "Sage Vishwamitra's Call",
    text: "Sage Vishwamitra requests young Rama and Lakshmana to guard the sacred forest yajnas. Trusting duty opens boundless horizons. Climb up to twenty-two.",
    valueOrLesson: "Virtue: Self-Belief & Devotion",
    scene: { svgType: "hanuman", primaryColor: "#f59e0b" },
  },
  4: {
    square: 4,
    kind: "story",
    chapter: "BALA KANDA",
    title: "Protecting the Hermitage",
    text: "In the Dandaka wilderness, Rama shields hermits and restores peace to the forest, learning that strength exists to protect the defenseless.",
    valueOrLesson: "Virtue: Protecting the Vulnerable",
    scene: { svgType: "default", primaryColor: "#10b981" },
  },
  5: {
    square: 5,
    kind: "story",
    chapter: "BALA KANDA",
    title: "Blessing of Celestial Divyastras",
    text: "Pleased with Rama's purity of intent, Sage Vishwamitra bestows divine celestial weapons that respond only to righteous thoughts.",
    valueOrLesson: "Virtue: Purity of Purpose",
    scene: { svgType: "default", primaryColor: "#6366f1" },
  },
  6: {
    square: 6,
    kind: "story",
    chapter: "BALA KANDA",
    title: "Arrival in Mithila",
    text: "The princes arrive in beautiful Mithila, kingdom of King Janaka, where fragrant mango groves and fountains welcome truth-seekers.",
    valueOrLesson: "Virtue: Respect for Culture",
    scene: { svgType: "ayodhya", primaryColor: "#ec4899" },
  },
  7: {
    square: 7,
    kind: "story",
    chapter: "BALA KANDA",
    title: "The Shiva Dhanush (Pinaka)",
    text: "In King Janaka's grand assembly, mighty kings cannot even budge the bow of Shiva. Rama lifts it gracefully with effortless composure.",
    valueOrLesson: "Virtue: Inner Strength over Pretense",
    scene: { svgType: "default", primaryColor: "#8b5cf6" },
  },
  8: {
    square: 8,
    kind: "ladder",
    chapter: "BALA KANDA",
    title: "Divine Wedding in Mithila",
    text: "Rama and Sita join hands around the holy flame, promising mutual respect and lifelong partnership. Climb up to twenty-six.",
    valueOrLesson: "Virtue: Partnership & Lifelong Love",
    scene: { svgType: "sugriva", primaryColor: "#10b981" },
  },
  9: {
    square: 9,
    kind: "story",
    chapter: "BALA KANDA",
    title: "Joyous Return to Ayodhya",
    text: "The royal procession returns to Ayodhya as citizens shower jasmine petals and drums beat in celebratory triumph.",
    valueOrLesson: "Virtue: Shared Joy with Society",
    scene: { svgType: "ayodhya", primaryColor: "#f59e0b" },
  },
  10: {
    square: 10,
    kind: "story",
    chapter: "AYODHYA KANDA",
    title: "Coronation Announced",
    text: "King Dasharatha announces that virtuous Rama shall be crowned crown prince (Yuvaraja). The streets glow with festive oil lamps.",
    valueOrLesson: "Virtue: Merit Recognized by Elders",
    scene: { svgType: "ayodhya", primaryColor: "#eab308" },
  },
  11: {
    square: 11,
    kind: "story",
    chapter: "AYODHYA KANDA",
    title: "Manthara's Whispers",
    text: "Jealous maid Manthara whispers doubts into Queen Kaikeyi's ear, showing how envy turns the happiest palace bitter.",
    valueOrLesson: "Lesson: Guarding the Mind from Gossip",
    scene: { svgType: "kaikeyi", primaryColor: "#ef4444" },
  },
  12: {
    square: 12,
    kind: "story",
    chapter: "AYODHYA KANDA",
    title: "Kaikeyi Demands Boons",
    text: "Remembering two ancient boons, Kaikeyi demands Bharata be crowned king and Rama be exiled to the forest for fourteen years.",
    valueOrLesson: "Lesson: The Danger of Sudden Selfishness",
    scene: { svgType: "kaikeyi", primaryColor: "#dc2626" },
  },
  13: {
    square: 13,
    kind: "story",
    chapter: "AYODHYA KANDA",
    title: "Dasharatha's Dilemma",
    text: "King Dasharatha is torn between fatherly affection and his sacred vow of truth. A solemn promise cannot be broken.",
    valueOrLesson: "Virtue: Integrity to One's Word",
    scene: { svgType: "default", primaryColor: "#b91c1c" },
  },
  14: {
    square: 14,
    kind: "story",
    chapter: "AYODHYA KANDA",
    title: "Rama's Calm Acceptance",
    text: "Hearing the decree, Rama smiles with serene love, comforting his weeping father and blessing his brother Bharata without any rancor.",
    valueOrLesson: "Virtue: Equanimity in Adversity",
    scene: { svgType: "default", primaryColor: "#059669" },
  },
  15: {
    square: 15,
    kind: "story",
    chapter: "AYODHYA KANDA",
    title: "Sita & Lakshmana Stand United",
    text: "Sita and Lakshmana refuse the comforts of Ayodhya, declaring that their palace is wherever Rama walks.",
    valueOrLesson: "Virtue: Undying Family Loyalty",
    scene: { svgType: "lakshmana", primaryColor: "#8b5cf6" },
  },
  16: {
    square: 16,
    kind: "story",
    chapter: "AYODHYA KANDA",
    title: "Farewell to the City",
    text: "Dressed in hermit bark garments, the trio depart into the woods as the weeping people of Ayodhya follow as far as the river.",
    valueOrLesson: "Virtue: Renunciation of Vanity",
    scene: { svgType: "default", primaryColor: "#64748b" },
  },
  17: {
    square: 17,
    kind: "snake",
    chapter: "AYODHYA KANDA",
    title: "Gentle Lesson — The Golden Deer",
    text: "Sita is charmed by an illusionary deer that conceals deception. Glamour often hides truth. Slide gently down to four and reflect with clear eyes.",
    valueOrLesson: "Lesson: Discernment over Glamour",
    scene: { svgType: "deer", primaryColor: "#f97316" },
  },
  18: {
    square: 18,
    kind: "story",
    chapter: "AYODHYA KANDA",
    title: "Guha Ferries Across the Ganga",
    text: "Nishada king Guha embraces Rama warmly and rows them across the sacred Ganges on wooden rafts, proving kinship transcends caste.",
    valueOrLesson: "Virtue: Universal Kinship & Equality",
    scene: { svgType: "bridge", primaryColor: "#0284c7" },
  },
  19: {
    square: 19,
    kind: "story",
    chapter: "AYODHYA KANDA",
    title: "Sage Bharadwaja at Prayag",
    text: "At Triveni Sangam, wise Sage Bharadwaja guides the travelers toward the tranquil mountain of Chitrakoot.",
    valueOrLesson: "Virtue: Seeking Wise Guidance",
    scene: { svgType: "default", primaryColor: "#0891b2" },
  },
  20: {
    square: 20,
    kind: "story",
    chapter: "AYODHYA KANDA",
    title: "Cottage at Chitrakoot",
    text: "Lakshmana builds a charming thatched hut by the Mandakini river amidst deer, peacocks, and flowering champaka trees.",
    valueOrLesson: "Virtue: Finding Peace in Simplicity",
    scene: { svgType: "default", primaryColor: "#16a34a" },
  },
  21: {
    square: 21,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "Bharata's Pilgrimage",
    text: "Returning to find what happened, Bharata refuses the crown and marches to Chitrakoot to implore Rama to return.",
    valueOrLesson: "Virtue: Selfless Brotherly Love",
    scene: { svgType: "default", primaryColor: "#d97706" },
  },
  22: {
    square: 22,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "The Sacred Padukas (Sandals)",
    text: "Rama counsels Bharata on royal duty. Bharata reverently takes Rama's wooden sandals to rule Ayodhya as his humble regent.",
    valueOrLesson: "Virtue: Leadership as Service",
    scene: { svgType: "default", primaryColor: "#f59e0b" },
  },
  23: {
    square: 23,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "Entering Dandakaranya",
    text: "Rama, Sita, and Lakshmana move deeper into the deep forest to avoid tempting Ayodhya visitors from following them.",
    valueOrLesson: "Virtue: Uncompromising Dedication",
    scene: { svgType: "default", primaryColor: "#047857" },
  },
  24: {
    square: 24,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "Sage Atri & Anasuya",
    text: "Elder ascetic Anasuya teaches Sita the eternal beauty of womanly strength and gifts her divine fragrant silks that never fade.",
    valueOrLesson: "Virtue: Grace & Inner Radiance",
    scene: { svgType: "default", primaryColor: "#a855f7" },
  },
  25: {
    square: 25,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "The Sages' Petition",
    text: "Forest hermits show Rama the remnants of their destroyed hermitages. Rama raises his right hand and vows lifelong protection to them.",
    valueOrLesson: "Virtue: Duty to Protect Society",
    scene: { svgType: "default", primaryColor: "#3b82f6" },
  },
  26: {
    square: 26,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "Sage Agastya's Quiver",
    text: "Great Sage Agastya welcomes Rama with celestial bows, inexhaustible quivers, and weapons forged for the ultimate victory of truth.",
    valueOrLesson: "Virtue: Preparedness for Trials",
    scene: { svgType: "default", primaryColor: "#4338ca" },
  },
  27: {
    square: 27,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "Peace at Panchavati",
    text: "On the banks of the murmuring Godavari river, they settle in Panchavati, living happily in harmony with nature.",
    valueOrLesson: "Virtue: Contentment in Nature",
    scene: { svgType: "default", primaryColor: "#15803d" },
  },
  28: {
    square: 28,
    kind: "ladder",
    chapter: "ARANYA KANDA",
    title: "Jatayu Pledges Protection",
    text: "The noble elder eagle Jatayu, old friend of King Dasharatha, offers to guard Sita and the cottage. Climb up to forty-seven.",
    valueOrLesson: "Virtue: Moral Bravery & Elder Bonds",
    scene: { svgType: "jatayu", primaryColor: "#0284c7" },
  },
  29: {
    square: 29,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "Surpanakha's Thwarting",
    text: "Ravana's sister Surpanakha tries to attack Sita in jealousy, but vigilant Lakshmana steps in to protect their home.",
    valueOrLesson: "Virtue: Constant Alertness",
    scene: { svgType: "lakshmana", primaryColor: "#dc2626" },
  },
  30: {
    square: 30,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "Battle of Janasthana",
    text: "Fourteen thousand demon warriors led by Khara attempt to overrun Panchavati; Rama single-handedly turns them back with divine courage.",
    valueOrLesson: "Virtue: Courage Against Impossible Odds",
    scene: { svgType: "default", primaryColor: "#b91c1c" },
  },
  31: {
    square: 31,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "Ravana's Envy Ignites",
    text: "Surpanakha flees to golden Lanka, telling ten-headed King Ravana of Sita's incomparable beauty and provoking his dark ambition.",
    valueOrLesson: "Lesson: Ego Breeds Destructive Desires",
    scene: { svgType: "ravana", primaryColor: "#7f1d1d" },
  },
  32: {
    square: 32,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "Maricha's Warning",
    text: "Maricha counsels Ravana that antagonizing Rama will lead to Lanka's ruin, but arrogant Ravana refuses to hear wise advice.",
    valueOrLesson: "Lesson: Arrogance Rejects Wise Counsel",
    scene: { svgType: "deer", primaryColor: "#c2410c" },
  },
  33: {
    square: 33,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "The Golden Deer Glitters",
    text: "Maricha disguises himself as an enchanting deer with sapphire eyes and golden skin, darting tantalizingly near Sita's grove.",
    valueOrLesson: "Lesson: Beware Superficial Allure",
    scene: { svgType: "deer", primaryColor: "#ea580c" },
  },
  34: {
    square: 34,
    kind: "snake",
    chapter: "ARANYA KANDA",
    title: "Gentle Lesson — Kaikeyi's Boons",
    text: "Words spoken in haste and anger cause deep trials. Speak with patience when your heart is unsettled. Slide gently down to twelve.",
    valueOrLesson: "Lesson: Patience in Anger",
    scene: { svgType: "kaikeyi", primaryColor: "#e11d48" },
  },
  35: {
    square: 35,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "The False Mendicant",
    text: "While Rama and Lakshmana are drawn away into the forest, Ravana approaches the hermitage disguised as an ascetic asking for alms.",
    valueOrLesson: "Lesson: Wolf in Sheep's Clothing",
    scene: { svgType: "rekha", primaryColor: "#991b1b" },
  },
  36: {
    square: 36,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "Crossing the Lakshmana Rekha",
    text: "Out of compassion for a hungry mendicant, Sita steps across the boundary line drawn for her safety. Ravana seizes her.",
    valueOrLesson: "Lesson: Respecting Prudent Boundaries",
    scene: { svgType: "rekha", primaryColor: "#b91c1c" },
  },
  37: {
    square: 37,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "Jatayu's Aerial Duel",
    text: "Hearing Sita's cry from the clouds, aged Jatayu soars into the sky, tearing Ravana's chariot with his talons and beak.",
    valueOrLesson: "Virtue: Selfless Defense of Others",
    scene: { svgType: "jatayu", primaryColor: "#0284c7" },
  },
  38: {
    square: 38,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "Jatayu Falls to Earth",
    text: "Ravana cuts Jatayu's wings with his sword. The valiant bird falls to the earth, clinging to his last breath to deliver word to Rama.",
    valueOrLesson: "Virtue: Heroism in Defeat",
    scene: { svgType: "jatayu", primaryColor: "#0369a1" },
  },
  39: {
    square: 39,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "Imprisonment in Ashoka Vatika",
    text: "Ravana imprisons Sita in Lanka's Ashoka garden surrounded by fierce guards. Sita sits beneath a tree, holding Rama in her heart.",
    valueOrLesson: "Virtue: Steadfast Faith under Duress",
    scene: { svgType: "default", primaryColor: "#475569" },
  },
  40: {
    square: 40,
    kind: "story",
    chapter: "ARANYA KANDA",
    title: "Sita's Unbroken Spirit",
    text: "Despite threats and lavish promises, Sita pays no heed to Ravana, placing a blade of grass before her to symbolize his insignificance.",
    valueOrLesson: "Virtue: Unshakeable Moral Dignity",
    scene: { svgType: "default", primaryColor: "#334155" },
  },
  41: {
    square: 41,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "The Empty Cottage",
    text: "Rama and Lakshmana return to find Panchavati deserted. Rama weeps for Sita, asking trees and rivers if they have seen her footprints.",
    valueOrLesson: "Virtue: Honest Human Emotion",
    scene: { svgType: "default", primaryColor: "#64748b" },
  },
  42: {
    square: 42,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Jatayu's Last Words",
    text: "They find dying Jatayu, who gasps: 'Ravana of Lanka has taken Sita southwards.' Rama strokes the brave eagle's feathers with tears.",
    valueOrLesson: "Virtue: Gratitude to Fallen Heroes",
    scene: { svgType: "jatayu", primaryColor: "#0284c7" },
  },
  43: {
    square: 43,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Last Rites for Jatayu",
    text: "Rama performs funeral rites for Jatayu with the reverence of a son, granting the noble bird moksha and liberation.",
    valueOrLesson: "Virtue: Honoring Those Who Sacrificed",
    scene: { svgType: "default", primaryColor: "#f59e0b" },
  },
  44: {
    square: 44,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "The Waters of Lake Pampa",
    text: "Marching south, they reach Lake Pampa, where swans glide upon cool water and white lotus flowers ease their burning grief.",
    valueOrLesson: "Virtue: Nature's Healing Solace",
    scene: { svgType: "ocean", primaryColor: "#0ea5e9" },
  },
  45: {
    square: 45,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Shabari's Ashram",
    text: "Elder hermit Shabari has waited her entire life for Rama. She tastes each forest berry first to ensure she offers only the sweetest fruit.",
    valueOrLesson: "Virtue: Pure, Unconditional Devotion",
    scene: { svgType: "shabari", primaryColor: "#84cc16" },
  },
  46: {
    square: 46,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Mount Rishyamukha",
    text: "Arriving at Mount Rishyamukha, exiled vanara king Sugriva spots two armed warriors and wonders if they are friends or foes.",
    valueOrLesson: "Virtue: Caution in Uncertain Times",
    scene: { svgType: "default", primaryColor: "#15803d" },
  },
  47: {
    square: 47,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Hanuman's Inquisitive Welcome",
    text: "Hanuman approaches disguised as a gentle brahmachari, speaking with such refined eloquence that Rama immediately trusts his noble heart.",
    valueOrLesson: "Virtue: Wisdom in Speech & Discernment",
    scene: { svgType: "hanuman", primaryColor: "#f59e0b" },
  },
  48: {
    square: 48,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Hanuman Unveils His Form",
    text: "Learning who they are, Hanuman bows in joyful prostration, placing Rama and Lakshmana on his broad shoulders to carry them to Sugriva.",
    valueOrLesson: "Virtue: Joy of Selfless Service",
    scene: { svgType: "hanuman", primaryColor: "#d97706" },
  },
  49: {
    square: 49,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Sita's Dropped Jewels",
    text: "Sugriva brings a cloth tied with jewels dropped by Sita from the chariot. Lakshmana recognizes only her anklets from touching her feet daily.",
    valueOrLesson: "Virtue: Pure Reverence for Elders",
    scene: { svgType: "default", primaryColor: "#eab308" },
  },
  50: {
    square: 50,
    kind: "ladder",
    chapter: "KISHKINDHA KANDA",
    title: "Alliance Around Sacred Fire",
    text: "Rama and Sugriva kindle a sacred fire, clasping hands and pledging eternal brotherhood and mutual aid. Climb up to seventy-one.",
    valueOrLesson: "Virtue: Collective Effort & Sacred Friendship",
    scene: { svgType: "sugriva", primaryColor: "#10b981" },
  },
  51: {
    square: 51,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Restoration of Kishkindha",
    text: "Rama helps restore justice in Kishkindha, reinstating Sugriva to his rightful kingdom while advising on fair and lawful governance.",
    valueOrLesson: "Virtue: Justice over Favoritism",
    scene: { svgType: "default", primaryColor: "#ca8a04" },
  },
  52: {
    square: 52,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Coronation of Sugriva",
    text: "Sugriva is crowned king, and brave young Angada is named Yuvaraja. Harmony returns to the monkey kingdom.",
    valueOrLesson: "Virtue: Order & Rebuilding Society",
    scene: { svgType: "ayodhya", primaryColor: "#eab308" },
  },
  53: {
    square: 53,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Monsoon in Mount Prasravana",
    text: "Torrential monsoon rains pause all travel. Rama and Lakshmana stay in a mountain cave, listening to thunder while waiting for the skies to clear.",
    valueOrLesson: "Virtue: Patience through Seasons of Waiting",
    scene: { svgType: "default", primaryColor: "#0284c7" },
  },
  54: {
    square: 54,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Autumn Summons the Legions",
    text: "As white clouds appear in clear autumn skies, Sugriva sounds the conch horn, summoning vanara hosts from mountains, forests, and valleys.",
    valueOrLesson: "Virtue: Fulfilling Promises on Time",
    scene: { svgType: "default", primaryColor: "#059669" },
  },
  55: {
    square: 55,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Search in Four Directions",
    text: "Sugriva dispatches four mighty search armies to the North, East, West, and South, detailing the geography of the known world.",
    valueOrLesson: "Virtue: Organized Strategic Planning",
    scene: { svgType: "default", primaryColor: "#2563eb" },
  },
  56: {
    square: 56,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Rama's Signet Ring",
    text: "Trusting Hanuman's deep wisdom, Rama entrusts him with his personal signet ring (Mudra) as an indisputable token for Sita.",
    valueOrLesson: "Virtue: Trust Built on Character",
    scene: { svgType: "default", primaryColor: "#f59e0b" },
  },
  57: {
    square: 57,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Shore of the Southern Ocean",
    text: "The southern army reaches the edge of the Indian peninsula. Before them stretches a roaring ocean with crashing waves and boundless depth.",
    valueOrLesson: "Virtue: Standing Before Massive Challenges",
    scene: { svgType: "ocean", primaryColor: "#0369a1" },
  },
  58: {
    square: 58,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Sampati's Vision",
    text: "Elder bird Sampati, brother of Jatayu, spots Lanka 100 yojanas across the water with his keen vision, confirming Sita lives there.",
    valueOrLesson: "Virtue: Collaboration of Different Generations",
    scene: { svgType: "jatayu", primaryColor: "#0284c7" },
  },
  59: {
    square: 59,
    kind: "story",
    chapter: "KISHKINDHA KANDA",
    title: "Jambavan Awakens Hanuman",
    text: "Wise bear king Jambavan reminds silent Hanuman of his divine heritage: 'You are the son of the Wind God; wake up to your limitless power!'",
    valueOrLesson: "Virtue: Inspiring Others to Greatness",
    scene: { svgType: "hanuman", primaryColor: "#f59e0b" },
  },
  60: {
    square: 60,
    kind: "story",
    chapter: "SUNDARA KANDA",
    title: "Mount Mahendra Ascent",
    text: "Hanuman expands his form like a golden mountain on Mount Mahendra, pressing his feet so hard into the rock that sweet spring waters burst forth.",
    valueOrLesson: "Virtue: Preparing Body & Soul for Grand Deeds",
    scene: { svgType: "hanuman", primaryColor: "#ea580c" },
  },
  61: {
    square: 61,
    kind: "story",
    chapter: "SUNDARA KANDA",
    title: "The Ocean Flight",
    text: "Hanuman leaps into the sky like an arrow from Rama's bow. Clouds trail behind him and ocean waves part below his radiant passage.",
    valueOrLesson: "Virtue: Fearless Single-Minded Focus",
    scene: { svgType: "hanuman", primaryColor: "#f59e0b" },
  },
  62: {
    square: 62,
    kind: "snake",
    chapter: "SUNDARA KANDA",
    title: "Gentle Lesson — The Boundary Line",
    text: "Crossing boundaries without care leads to unnecessary peril. Care for rules that safeguard your journey. Slide gently down to forty-one.",
    valueOrLesson: "Lesson: Respecting Boundaries",
    scene: { svgType: "rekha", primaryColor: "#ef4444" },
  },
  63: {
    square: 63,
    kind: "story",
    chapter: "SUNDARA KANDA",
    title: "Surasa's Riddle",
    text: "Surasa tests Hanuman's wit by opening her jaws wide. Hanuman expands huge, then instantly shrinks tiny to enter and exit before she can blink.",
    valueOrLesson: "Virtue: Agility of Mind over Brute Force",
    scene: { svgType: "hanuman", primaryColor: "#0d9488" },
  },
  64: {
    square: 64,
    kind: "story",
    chapter: "SUNDARA KANDA",
    title: "Landing in Lanka",
    text: "Hanuman touches down on Mount Lamba on the shores of Lanka, shrinking to the size of a cat so as not to alert the fortress sentinels.",
    valueOrLesson: "Virtue: Discretion & Prudence",
    scene: { svgType: "default", primaryColor: "#475569" },
  },
  65: {
    square: 65,
    kind: "story",
    chapter: "SUNDARA KANDA",
    title: "Midnight Search in Golden Lanka",
    text: "Hanuman explores palaces, banquet halls, and armories under moonlight, marveling at the architecture while seeking only Mother Sita.",
    valueOrLesson: "Virtue: Unswerving Focus on the Mission",
    scene: { svgType: "default", primaryColor: "#334155" },
  },
  66: {
    square: 66,
    kind: "ladder",
    chapter: "SUNDARA KANDA",
    title: "Discovering Sita in Ashoka Vatika",
    text: "Hanuman finds Sita seated in meditation under a Shimshapa tree, glowing with dignity like a flame in the smoke. Climb up to eighty-five.",
    valueOrLesson: "Virtue: Purity of Soul & Enduring Hope",
    scene: { svgType: "shabari", primaryColor: "#84cc16" },
  },
  67: {
    square: 67,
    kind: "story",
    chapter: "SUNDARA KANDA",
    title: "Singing Rama's Praise",
    text: "Sitting high in the leafy branches, Hanuman gently sings the lineage of Raghu and Rama's noble deeds in a sweet, comforting voice.",
    valueOrLesson: "Virtue: Kindness to the Grieving Heart",
    scene: { svgType: "hanuman", primaryColor: "#d97706" },
  },
  68: {
    square: 68,
    kind: "story",
    chapter: "SUNDARA KANDA",
    title: "Delivering the Mudra Ring",
    text: "Hanuman climbs down, shows Rama's signet ring, and speaks with folded hands. Sita weeps tears of boundless relief.",
    valueOrLesson: "Virtue: Delivering Hope to Despair",
    scene: { svgType: "hanuman", primaryColor: "#f59e0b" },
  },
  69: {
    square: 69,
    kind: "story",
    chapter: "SUNDARA KANDA",
    title: "Sita's Chudamani Jewel",
    text: "Sita removes her precious hair jewel (Chudamani) and gives it to Hanuman, instructing him: 'Tell Rama I will survive waiting for his coming.'",
    valueOrLesson: "Virtue: Courageous Fortitude",
    scene: { svgType: "default", primaryColor: "#ec4899" },
  },
  70: {
    square: 70,
    kind: "story",
    chapter: "SUNDARA KANDA",
    title: "Challenging Lanka's Pride",
    text: "Before departing, Hanuman uproots the groves of arrogance, declaring to Ravana's ministers that Rama's justice is on the horizon.",
    valueOrLesson: "Virtue: Moral Boldness Against Injustice",
    scene: { svgType: "hanuman", primaryColor: "#b91c1c" },
  },
  71: {
    square: 71,
    kind: "story",
    chapter: "SUNDARA KANDA",
    title: "The Burning of Lanka",
    text: "Ravana attempts to set Hanuman's tail alight with oiled cloth. Hanuman uses it to burn the citadels of pride across the island.",
    valueOrLesson: "Virtue: Turning Malice into Defense",
    scene: { svgType: "hanuman", primaryColor: "#ea580c" },
  },
  72: {
    square: 72,
    kind: "story",
    chapter: "SUNDARA KANDA",
    title: "The Leap Back",
    text: "Cooling his tail in the sea, Hanuman leaps back across the ocean, roaring in joy: 'Drishta Sita!' ('I have seen Mother Sita!').",
    valueOrLesson: "Virtue: Joy in Successful Duty",
    scene: { svgType: "ocean", primaryColor: "#0284c7" },
  },
  73: {
    square: 73,
    kind: "story",
    chapter: "SUNDARA KANDA",
    title: "Rejoicing at Madhuvana",
    text: "The returning southern army celebrates in Sugriva's royal honey orchard, tasting golden honey before reporting to Rama.",
    valueOrLesson: "Virtue: Celebrating Team Achievement",
    scene: { svgType: "default", primaryColor: "#eab308" },
  },
  74: {
    square: 74,
    kind: "story",
    chapter: "SUNDARA KANDA",
    title: "Rama Embraces Hanuman",
    text: "Hanuman places Sita's jewel in Rama's hands. Rama embraces Hanuman with tears of profound gratitude, declaring he is forever indebted.",
    valueOrLesson: "Virtue: Humble Gratitude from Leaders",
    scene: { svgType: "hanuman", primaryColor: "#f59e0b" },
  },
  75: {
    square: 75,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "March of the Vanara Host",
    text: "Under Rama, Lakshmana, and Sugriva, millions of vanaras march southward like a golden river, shaking the earth with resolve.",
    valueOrLesson: "Virtue: Unity of Diverse Peoples",
    scene: { svgType: "default", primaryColor: "#d97706" },
  },
  76: {
    square: 76,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Encamping by the Ocean",
    text: "The army encamps along the vast southern beach, gazing across the waves toward the distant fortifications of Lanka.",
    valueOrLesson: "Virtue: Clear View of the Objective",
    scene: { svgType: "ocean", primaryColor: "#0284c7" },
  },
  77: {
    square: 77,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Vibhishana Seeks Refuge",
    text: "Ravana's righteous brother Vibhishana urges him to return Sita; when kicked from court, he flies across the ocean seeking Rama's shelter.",
    valueOrLesson: "Virtue: Choosing Truth over Blind Loyalty",
    scene: { svgType: "default", primaryColor: "#10b981" },
  },
  78: {
    square: 78,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Rama's Promise of Sanctuary",
    text: "When commanders urge suspicion, Rama declares: 'Even if Ravana himself came seeking protection, I would grant it without hesitation.'",
    valueOrLesson: "Virtue: Absolute Compassion & Sanctuary",
    scene: { svgType: "default", primaryColor: "#059669" },
  },
  79: {
    square: 79,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Counsel of Ocean Deity Varuna",
    text: "The ocean god Varuna arises from the waves with folded hands, advising Rama that stones placed by architect Nala will float upon the water.",
    valueOrLesson: "Virtue: Respect for Natural Elements",
    scene: { svgType: "ocean", primaryColor: "#0284c7" },
  },
  80: {
    square: 80,
    kind: "ladder",
    chapter: "YUDDHA KANDA",
    title: "Building the Rama Setu Bridge",
    text: "Vanaras carve stones inscribed with 'RAMA'. Even a tiny squirrel carries grains of sand. In 5 days, a miraculous bridge spans the sea! Climb up to ninety-nine.",
    valueOrLesson: "Virtue: Unconditional Duty & Collective Power",
    scene: { svgType: "bridge", primaryColor: "#0ea5e9" },
  },
  81: {
    square: 81,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Army Crosses to Lanka",
    text: "The grand army marches triumphantly across the bridge of stones, setting up camp on Mount Suvela overlooking Lanka's gates.",
    valueOrLesson: "Virtue: Triumph of Cooperative Effort",
    scene: { svgType: "bridge", primaryColor: "#0284c7" },
  },
  82: {
    square: 82,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Angada's Peace Mission",
    text: "Even on the brink of battle, Rama sends Angada to offer peaceful surrender; arrogant Ravana rejects peace.",
    valueOrLesson: "Virtue: Exhausting All Peaceful Avenues",
    scene: { svgType: "default", primaryColor: "#d97706" },
  },
  83: {
    square: 83,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "The Battle Begins",
    text: "Drums thunder and conches roar. Vanaras scale the battlements as both armies clash in the ultimate contest between righteousness and tyranny.",
    valueOrLesson: "Virtue: Standing Firm in the Hour of Crisis",
    scene: { svgType: "default", primaryColor: "#b91c1c" },
  },
  84: {
    square: 84,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Indrajit's Nagapasha Snare",
    text: "Sorcerer prince Indrajit binds Rama and Lakshmana with venomous serpent darts (Nagapasha). Grief sweeps through the camp.",
    valueOrLesson: "Virtue: Enduring Deep Adversity",
    scene: { svgType: "default", primaryColor: "#7f1d1d" },
  },
  85: {
    square: 85,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Garuda's Descent",
    text: "Celestial eagle Garuda descends with wings like blazing suns; the serpent bonds instantly dissolve and flee before his majesty.",
    valueOrLesson: "Virtue: Faith that Relief Will Arrive",
    scene: { svgType: "jatayu", primaryColor: "#0284c7" },
  },
  86: {
    square: 86,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Awakening of Kumbhakarna",
    text: "Desperate, Ravana orders his titan brother Kumbhakarna awakened from his months of deep sleep with trumpets and herds of elephants.",
    valueOrLesson: "Lesson: Inaction in Critical Hours Has Consequences",
    scene: { svgType: "sleep", primaryColor: "#64748b" },
  },
  87: {
    square: 87,
    kind: "snake",
    chapter: "YUDDHA KANDA",
    title: "Gentle Lesson — Ravana's Pride",
    text: "Ravana had learned scholarship, yet stubborn ego deafened his counsel. Pride blinds the wisest minds. Slide gently down to sixty-eight.",
    valueOrLesson: "Lesson: Humility over Ego",
    scene: { svgType: "ravana", primaryColor: "#b91c1c" },
  },
  88: {
    square: 88,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Lakshmana Defeats Indrajit",
    text: "Lakshmana disrupts Indrajit's secret sacrificial altar at Nikumbhila, relying on truth and devotion to defeat the master of illusions.",
    valueOrLesson: "Virtue: Moral Purity Overcomes Sorcery",
    scene: { svgType: "lakshmana", primaryColor: "#8b5cf6" },
  },
  89: {
    square: 89,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "The Shakti Spear",
    text: "Ravana strikes Lakshmana with the deadly Shakti spear. Physician Sushena declares only the Sanjeevani herb can revive him before dawn.",
    valueOrLesson: "Virtue: Brotherly Grief & Urgency",
    scene: { svgType: "lakshmana", primaryColor: "#ef4444" },
  },
  90: {
    square: 90,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Hanuman Carries Mount Dronagiri",
    text: "Unable to identify the herb in the dark Himalayan night, Hanuman lifts the entire mountain of healing herbs on his palm and flies back!",
    valueOrLesson: "Virtue: Creative Solution to Save Lives",
    scene: { svgType: "sanjeevani", primaryColor: "#10b981" },
  },
  91: {
    square: 91,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Lakshmana Revived at Dawn",
    text: "The sweet fragrance of the Sanjeevani herb revives Lakshmana like one waking from sleep. Cheers erupt across the ocean beach.",
    valueOrLesson: "Virtue: Victory of Hope over Despair",
    scene: { svgType: "sanjeevani", primaryColor: "#059669" },
  },
  92: {
    square: 92,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "The Aditya Hridaya Hymn",
    text: "Sage Agastya imparts the sacred Aditya Hridaya prayer to Rama, invoking the eternal Sun that dispels darkness from inside and out.",
    valueOrLesson: "Virtue: Divine Meditation Before Duty",
    scene: { svgType: "ayodhya", primaryColor: "#f59e0b" },
  },
  93: {
    square: 93,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Indra's Chariot Arrives",
    text: "Seeing Ravana fighting from a chariot while Rama stands on foot, Lord Indra sends his golden chariot and charioteer Matali to Rama.",
    valueOrLesson: "Virtue: Righteousness Draws Celestial Help",
    scene: { svgType: "default", primaryColor: "#eab308" },
  },
  94: {
    square: 94,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "The Final Duel",
    text: "Rama and Ravana engage in a clash of titans that stills the winds. Whenever a head is severed, another springs from Ravana's ego.",
    valueOrLesson: "Virtue: Tireless Persistence Against Tyranny",
    scene: { svgType: "ravana", primaryColor: "#dc2626" },
  },
  95: {
    square: 95,
    kind: "snake",
    chapter: "YUDDHA KANDA",
    title: "Gentle Lesson — Kumbhakarna's Slumber",
    text: "Kumbhakarna slumbered while his kingdom needed truthful awakening. Inaction carries high cost. Slide gently down to seventy-six.",
    valueOrLesson: "Lesson: Timely Responsibility",
    scene: { svgType: "sleep", primaryColor: "#64748b" },
  },
  96: {
    square: 96,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "The Brahmastra Pierces Illusion",
    text: "Recalling Agastya's guidance, Rama releases the Brahmastra into Ravana's heart where the nectar of life was hidden. The tyrant falls.",
    valueOrLesson: "Virtue: Ultimate Victory of Dharma",
    scene: { svgType: "default", primaryColor: "#f59e0b" },
  },
  97: {
    square: 97,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Coronation of Vibhishana",
    text: "Rama crowns righteous Vibhishana king of Lanka and commands that Ravana receive full royal funeral rites: 'Enmity ends with death.'",
    valueOrLesson: "Virtue: Magnanimity in Victory",
    scene: { svgType: "default", primaryColor: "#10b981" },
  },
  98: {
    square: 98,
    kind: "story",
    chapter: "YUDDHA KANDA",
    title: "Reunion with Sita",
    text: "Sita is brought forth in radiant honor, reunited with Rama amidst joy that echoes from the mountains to the sea.",
    valueOrLesson: "Virtue: Vindicated Truth & Dignity",
    scene: { svgType: "ayodhya", primaryColor: "#ec4899" },
  },
  99: {
    square: 99,
    kind: "story",
    chapter: "UTTARA KANDA",
    title: "The Pushpaka Vimana Flights North",
    text: "Rama, Sita, Lakshmana, Hanuman, and Sugriva board the celestial flying chariot, soaring across mountains, Setu, and rivers toward Ayodhya.",
    valueOrLesson: "Virtue: Homecoming After Trials",
    scene: { svgType: "ayodhya", primaryColor: "#f59e0b" },
  },
  100: {
    square: 100,
    kind: "victory",
    chapter: "CORONATION",
    title: "Ramrajya — Festival of Lights",
    text: "In Ayodhya, Bharata crowns Rama with the sacred padukas. Diyas glow in every window, establishing a kingdom of peace, truth, and universal love!",
    valueOrLesson: "Ultimate Truth: Light Dispels Darkness",
    scene: { svgType: "victory", primaryColor: "#f59e0b" },
  },
};

export const RAMAYANA_MOMENTS: Moment[] = Object.values(RAMAYANA_STORYLINE);

export const DISCOVERY_FACTS: string[] = [
  "Discovery Fact: Moksha Patam (ancient Snakes & Ladders) originated in ancient India as an ethical teaching board where ladders represented virtues like generosity and snakes represented pride.",
  "Discovery Fact: The Ramayana is preserved in more than 300 regional traditions across South & Southeast Asia, including Thai Ramakien, Cambodian Reamker, and Indonesian Wayang.",
  "Discovery Fact: The legend of the Indian Palm Squirrel carrying pebbles for Rama's Setu bridge gave rise to the folk tale explaining its three white back stripes.",
  "Discovery Fact: In Braille notation, each numeral is derived from letters A through J, tactilely decipherable through raised dot configurations read with sensitive fingertips.",
];

export const STORY_CARDS = [
  {
    id: "ramayana",
    label: "Ramayana",
    subtitle: "Epic of Dharma, Valor & Compassion",
    cardColor: "#9a3412",
    accentColor: "#f59e0b",
    available: true,
  },
  {
    id: "mahabharata",
    label: "Mahabharata",
    subtitle: "Tale of Duty, Destiny & Wisdom",
    cardColor: "#1e3a8a",
    accentColor: "#60a5fa",
    available: false,
  },
  {
    id: "panchatantra",
    label: "Panchatantra",
    subtitle: "Timeless Fables of Animal Wit",
    cardColor: "#14532d",
    accentColor: "#4ade80",
    available: false,
  },
  {
    id: "freedom",
    label: "Freedom Fighters",
    subtitle: "Courage & Sacrifice of India's Heroes",
    cardColor: "#701a75",
    accentColor: "#f472b6",
    available: false,
  },
] as const;

export type StoryId = (typeof STORY_CARDS)[number]["id"];

export const momentFor = (square: Cell): Moment | undefined =>
  RAMAYANA_STORYLINE[square];

export const PLAYER_COLORS = [
  "#ef4444", // Crimson Red
  "#10b981", // Emerald Green
  "#3b82f6", // Royal Blue
  "#f59e0b", // Golden Amber
];

export const PLAYER_NAMES = ["Player 1", "Player 2", "Player 3", "Player 4"];

/** Row/col (0-indexed from top-left) for a square in boustrophedon order. */
export function cellPosition(square: Cell) {
  const index = square - 1;
  const rowFromBottom = Math.floor(index / 10);
  const row = 9 - rowFromBottom;
  const withinRow = index % 10;
  const col = rowFromBottom % 2 === 0 ? withinRow : 9 - withinRow;
  return { row, col };
}

/**
 * Standard 6-Dot Braille Patterns for Digits (0–9).
 */
export const BRAILLE_DIGIT_DOTS: Record<string, [boolean, boolean, boolean, boolean, boolean, boolean]> = {
  "1": [true, false, false, false, false, false],
  "2": [true, true, false, false, false, false],
  "3": [true, false, false, true, false, false],
  "4": [true, false, false, true, true, false],
  "5": [true, false, false, false, true, false],
  "6": [true, true, false, true, false, false],
  "7": [true, true, false, true, true, false],
  "8": [true, true, false, false, true, false],
  "9": [false, true, false, true, false, false],
  "0": [false, true, false, true, true, false],
};

/** Returns the 6-dot Braille patterns for every digit of the number. */
export function getBrailleDotsForNumber(num: number): Array<[boolean, boolean, boolean, boolean, boolean, boolean]> {
  const str = String(num);
  return str.split("").map((digit) => BRAILLE_DIGIT_DOTS[digit] ?? [false, false, false, false, false, false]);
}

/** Hardware Internals Specification for the Technical View */
export const HARDWARE_INTERNALS = {
  mcu: {
    name: "ESP32-WROOM-32",
    desc: "Dual-Core 240MHz MCU with 520KB SRAM, handles game logic, SPI dual-display rendering & audio synchronization.",
    voltage: "3.3V Logic",
  },
  diceDisplay: {
    name: "GC9A01 1.28\" Round TFT",
    desc: "240x240 RGB circular display with IPS wide viewing angle, driven over high-speed hardware SPI bus.",
    interface: "SPI: MOSI (GPIO 23), SCK (GPIO 18), CS (GPIO 15), DC (GPIO 2)",
  },
  storyDisplay: {
    name: "ILI9341 2.4\" Rectangular TFT",
    desc: "240x320 color LCD providing visual scene illustration, chapter subtitle, and moral lessons for deaf/hard-of-hearing players.",
    interface: "SPI: MOSI (GPIO 23), SCK (GPIO 18), CS (GPIO 5), DC (GPIO 4)",
  },
  rfid: {
    name: "RC522 13.56MHz RFID Reader",
    desc: "Near-field communication reader detecting passive NTAG213 story-card tags placed on the wooden tap zone.",
    interface: "SPI: MOSI (GPIO 23), MISO (GPIO 19), SCK (GPIO 18), SDA/CS (GPIO 21)",
  },
  audio: {
    name: "DFPlayer Mini + MicroSD",
    desc: "Hardware MP3 audio decoder with FAT32 MicroSD card slot storing regional voice narration files.",
    interface: "UART2: TX (GPIO 17), RX (GPIO 16)",
  },
  speaker: {
    name: "3W 4Ω Neodymium Driver + PAM8403",
    desc: "Class-D amplifier delivering crisp acoustic playback through the CNC-drilled circular speaker grille.",
  },
  controls: {
    name: "Tactile Navigation & Arcade Roll",
    desc: "Heavy-duty 40mm arcade microswitch for dice roll (GPIO 34), plus 4 tactile accessibility buttons with debouncing (GPIOs 35, 32, 33, 25).",
  },
  leds: {
    name: "Player Turn Indicator LEDs",
    desc: "4 diffused 5mm indicator LEDs recessed into the board face showing the active player turn (GPIOs 12, 13, 14, 27).",
  },
  power: {
    name: "Li-ion 18650 + TP4056 BMS",
    desc: "2600mAh rechargeable cell with USB-C charging, step-up boost converter to 5V and low-dropout 3.3V regulation.",
  },
};
